import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "piti.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen text-gray-900 bg-gray-100`}>
        {children}     
      </body>
    </html>
  );
}
